language: python
python:
- 2.6
- 2.7
install:
- pip install coveralls
script:
- nosetests --cover-package=pyblish --with-doctest --with-coverage --exclude=vendor
- pip install git+git://github.com/abstractfactory/pyblish.git
after_success:
- coveralls
deploy:
  provider: pypi
  user: mottosso
  password: OA0LmiLkryLgxGebvs7uwv/rExnL4KnCeiMBK9P42qgKwE9aLQY3Y+iB94gy0Q/ziPGm8zASAHeCUIwmbmRleQEvAXdoDIFdl59vRBkocDKc2Ya3Nqw9zwBm5ExDZeuj23JcWl18rH8XNd7HTyRaOZisZ4aZfG/2k++ylvOCZYU=
  on:
    tags: true
